import Layout from "@/components/Layout";
import "@/app/globals.css";
import Script from "next/script";
import { cookies } from "next/headers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="beforeInteractive"
          src="https://kit.fontawesome.com/dc3bbac095.js"
        />
      </head>
      <body>
        <Layout theme={"light" || cookies().get("theme")?.value}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
